# 主题设置
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# 站点基本设置
locale: "en-US"
title: "Welcome to Luciusite"
title_separator: "-"
subtitle: "Magical World of Mine"
name: "Donghao(Lucius)Wu"
description: "In this site, you can see a lot of random but interesting stuff"
url: "https://github.com/donghao-wu/donghao-wu.github.io"
repository: "donghao-wu/donghao-wu.github.io"
teaser: "/assets/images/test2.png"
logo: "/assets/images/logo3.png"
masthead_title: "Luciusite"
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true

# 导航栏设置
navigation:
  header: main
  footer: main

# **关键：确保 `/cn/` 目录使用 `cn-main`**
defaults:
  - scope:
      path: "_pages/cn"
      type: "pages"
    values:
      navigation:
        header: cn-main

  - scope:
      path: "_pages"
      type: "pages"
    values:
      navigation:
        header: main
      permalink: "/:title/"  # 确保 `/index.md` 仍然是 `/`

# 文章评论（可根据需要启用）
comments:
  provider: false

# 搜索功能
search: true
search_provider: lunr

# 侧边栏设置
sidebar:
  nav: "projects"
  show: true

# SEO 相关设置
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# 社交媒体分享
social:
  type: Person
  links:
    - "https://github.com/donghao-wu"
    - "https://www.linkedin.com/in/donghao-wu-a5a609237/"

# 网站作者信息
author:
  name: "Donghao (Lucius) Wu"
  avatar: "/assets/images/author.png"
  bio: "I love exploring Data Science, Machine Learning, and Data Visualization."
  location: "Somewhere on Earth"
  email: "donghao@uchicago.edu"

# 页脚信息
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/donghao-wu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/donghao-wu-a5a609237/"

# 读取文件设置
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp

# 编码格式
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown 解析
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# SCSS 设置
sass:
  sass_dir: _sass
  style: compressed

# 页面 URL 结构
permalink: /:categories/:title/

# 分页设置
paginate: 5
paginate_path: /page:num/

# Jekyll 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Mimic GitHub Pages 安全模式
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 归档设置
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML 压缩
compress_html:
  clippings: all
  ignore:
    envs: development
